changelog:
  categories:
    - title: Enhancement
      label:
        - enhancement
    - title: Bug Fixes
      label:
        - bug
        - fixes
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot
