name: Comment
on:
  push:
    branches:
      - test

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    if: github.run_number == 1
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "World, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
