name: Contexts
on:
  push
jobs:
  print: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.run_id }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.workspace }}"
      - run: echo "${{ github.repositoty }}"
      - run: echo "${{ github.repositoty_owner }}"
      - run: echo "${{ github.event }}"
