name: Cross repo
on:
  push:
    branches:
      - test
env:
  TARGET_REPO: 'github-actions-put-into-practice'
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      # GitGub App token Actionを使う場合
      # - id: create
      #   uses: actions/create-github-app-token@v1
      #   with:
      #     app-id: ${{ secrets.APP_ID }}
      #     private-key: ${{ secrets.PRIVATE_KEY }}
      #     repositories: ${{ env.TARGET_REPO }}

      # Scriptでトークンを取得する場合
      - uses: actions/checkout@v4
      - id: create
        run: .github/scripts/token.sh
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner}}/${{ env.TARGET_REPO }}
          path: ${{ env.TARGET_REPO }}
          token: ${{ steps.create.outputs.token }}
      - run: cat "${{ env.TARGET_REPO }}/README.md"

      # 即時失効APIの実行
      # - run: |
      #     curl --location --silint --request DELETE \
      #       --url ${GITHUB_API_URL}/installation/token" \
      #       --header "Accept: application/vnd.github.v3+json" \
      #       --header "X-GitHub-Api-Version: 2022-11-28" \
      #       --header "Authorization: Bearer ${TOKEN}"
      #   env:
      #     TOKEN: ${{ steps.create.outputs.token }}
