name: GITHUB_OUTPUT
on:
  push:
    branches:
      - main
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env:
          RESULT: ${{ steps.source.outputs.result }}
        run: echo "${RESULT}"
    # まとめるとこんな感じ
    # - id: <step-id>
    #   run: echo "<key>=<value>" >> "${GITHUB_OUTPUT}"
    #   ${{ steps.<step-id>.outputs.<key> }}
