name: Hello
on:
  push:
    branches:
      - test
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: |
          git log -1
          tree -a .
