name: Log group
on:
  push:
    branches:
      - test
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Show environment variables"
          printenv
          echo "::endgroup::"
