name: Prevent secrity misconfigurations
on:
  push:
    branches:
      - test
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.27.0
        with:
          scan-type: config
          severity: CRITICAL,HIGH
          exit-code: 1
